project:
  type: website

website:
  title: "AAC Website"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: AACweb2.qmd
        text: Analysis

format:
  html:
    theme: cosmo